name: Node CI

on: [push, pull_request, create]

jobs:

  # Test the build
  build:
    # Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x] #[8.x, 10.x, 12.x]
        os: [ubuntu-latest] #[windows-latest, ubuntu-latest, macOS-latest]

    # Go
    steps:
    - uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Versions
      run: node --version

    - name: Install
      run: npm install

    - name: Test
      run: npm test

  # ----- Only proceed beyond this point for new git tags ----- #

  # Publish to package registries
  publish:
    # Setup
    needs: build
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    # Go
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm ci

      # Publish to npm
      - name: Publish @RC to npm
        if: contains(github.ref, 'RC')
        # run: echo this is an @RC release!
        run: npm publish --tag RC
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Publish @latest to npm
        if: contains(github.ref, 'RC') == false #'!contains()'' doesn't work lol
        run: echo this is an @latest release!
        # run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      # Set up Node again, this time using GitHub as the publish target
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      # Publish to GitHub
      - name: Publish @RC to GitHub
        if: contains(github.ref, 'RC')
        # run: echo this is an @RC release!
        run: npm publish --tag RC
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish @latest to GitHub
        if: contains(github.ref, 'RC') == false #'!contains()'' doesn't work lol
        run: echo this is an @latest release!
        # run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
