name: Node CI

on:
  - push:
      tags-ignore:
        - *
  - pull_request:
      tags-ignore:
        - *

jobs:
  # Test the build
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Versions
      run: node --version

    - name: Install
      run: npm install

    - name: Test
      run: npm test
